// AUTH ACTIONS
export const USER_LOGIN = "USER_LOGIN";
export const START_AUTH = "START_AUTH";
export const END_AUTH = "END_AUTH";
export const USER_LOGOUT = "USER_LOGOUT";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const START_GET_PRODUCT_DETAIL = "START_GET_PRODUCT_DETAIL";
export const END_GET_PRODUCT_DETAIL = "END_GET_PRODUCT_DETAIL";
export const GET_WAREHOUSE = "GET_WAREHOUSE";

export const START_GET_PROVINCE = "START_GET_PROVINCE";
export const GET_PROVINCE = "GET_PROVINCE";
export const END_GET_PROVINCE = "END_GET_PROVINCE";

export const START_GET_CITY_BY_PROV_ID = "START_GET_CITY_BY_PROV_ID";
export const GET_CITY_BY_PROV_ID = "GET_CITY_BY_PROV_ID";
export const END_GET_CITY_BY_PROV_ID = "END_GET_CITY_BY_PROV_ID";

export const START_GET_ONGKIR = "START_GET_ONGKIR";
export const GET_ONGKIR = "GET_ONGKIR";
export const END_GET_ONGKIR = "END_GET_ONGKIR";
